### ISSUE TITLE
Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by FunnyDevs** [protyposis/ITEC-MediaPlayer#16]
I found this error when i use your mediaplayer inside a recyclerview. If i fling fast the recyclerview, the error occurs in mediaplayer.
This is the stacktrace

`
android.media.MediaCodec$CodecException: Error 0xffffffea
                                                                       at android.media.MediaCodec.native_configure(Native Method)
                                                                       at android.media.MediaCodec.configure(MediaCodec.java:577)
                                                                       at at.aau.itec.android.mediaplayer.MediaCodecVideoDecoder.configureCodec(MediaCodecVideoDecoder.java:51)
                                                                       at at.aau.itec.android.mediaplayer.MediaCodecDecoder.reinitCodec(MediaCodecDecoder.java:166)
                                                                       at at.aau.itec.android.mediaplayer.MediaCodecVideoDecoder.<init>(MediaCodecVideoDecoder.java:45)
                                                                       at at.aau.itec.android.mediaplayer.MediaPlayer.prepare(MediaPlayer.java:245)
                                                                       at at.aau.itec.android.mediaplayer.MediaPlayer$2.run(MediaPlayer.java:307)
                                                                       at java.lang.Thread.run(Thread.java:818)
05-06 10:38:04.440 9443-11645/com.funnydevs.hoop E/AndroidRuntime: Error reporting crash
                                                                   java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                       at android.os.Handler.<init>(Handler.java:200)
                                                                       at android.os.Handler.<init>(Handler.java:114)
                                                                       at android.content.AsyncQueryHandler.<init>(AsyncQueryHandler.java:125)
                                                                       at net.oneplus.odm.insight.tracker.AbstractTracker$TrackerAsyncQueryHandler.<init>(AbstractTracker.java:110)
                                                                       at net.oneplus.odm.insight.tracker.AbstractTracker.<init>(AbstractTracker.java:60)
                                                                       at net.oneplus.odm.insight.tracker.AppTracker.<init>(AppTracker.java:24)
                                                                       at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:99)
                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
`

I think the error is due to the thread that works even if the surface is abandoned, but i can't understand how to resolve it

**Comment by protyposis** [comment]
This exception happens during `prepare()` called from a thread in `prepareAsync()`. To work around this issue, take a look at the [prepareAsync() code](https://github.com/protyposis/ITEC-MediaPlayer/blob/v2.2.0/MediaPlayer/src/main/java/at/aau/itec/android/mediaplayer/MediaPlayer.java#L293), implement this method yourself (call `prepare()` from your own thread), and catch the `CodecException`. Does this problem only happen in ITEC-MediaPlayer or in Android's MediaPlayer as well?

Btw., I don't know the purpose of your app, but repeatedly initializing MediaPlayers from a RecyclerView doesn't seem like the best design choice to me, as this is a pretty costly call and the number of codec instances is limited and depends on the video format/resolution. Might be better to keep one MediaPlayer instance and only browse the data sources through the RecyclerView.

**Comment by FunnyDevs** [comment]
This happen only in ITEC-Mediaplayer.
I have thought to work with only one istances but preparing multiple istances makes app fast (an example is facebook and twitter apps, where video lists load quickly).
However i'll try your solution with the codecException

**Comment by protyposis** [comment]
Ok, please let me know if it works!

**Comment by FunnyDevs** [comment]
Yes, now it works! Thanks
