### ISSUE TITLE
Screen Rotation Error

### ISSUE THREAD

**Issue by saeednt** [protyposis/ITEC-MediaPlayer#35]
Hi!
I am using your library and it works fine. But when i try to rotate the screen i face this exception:
```
MediaPlayer: decoder error, too many instances?
android.media.MediaCodec$CodecException: Error 0xfffffff3
at android.media.MediaCodec.releaseOutputBuffer(Native Method)
at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2485)
at net.protyposis.android.mediaplayer.MediaCodecVideoDecoder.releaseFrame(MediaCodecVideoDecoder.java:116)
at net.protyposis.android.mediaplayer.MediaCodecVideoDecoder.renderFrame(MediaCodecVideoDecoder.java:87)
at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.renderVideoFrame(MediaPlayer.java:1173)
at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.loopInternal(MediaPlayer.java:974)
at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.handleMessage(MediaPlayer.java:826)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)

AndroidRuntime: FATAL EXCEPTION: MediaPlayer#PlaybackThread
android.media.MediaCodec$CodecException: Error 0xfffffff3
at android.media.MediaCodec.releaseOutputBuffer(Native Method)
at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2424)
at net.protyposis.android.mediaplayer.MediaCodecDecoder.releaseFrame(MediaCodecDecoder.java:432)
at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.releaseInternal(MediaPlayer.java:1119)
at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.handleMessage(MediaPlayer.java:856)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
```
Would you please help me figure this out?

**Comment by protyposis** [comment]
Seems like your device does not support multiple codec instances and it creates a new one before the previous one is released.

Are you calling `release()` when your activity stops? Is rotation working in the MediaPlayer-Extended demo app?

**Comment by saeednt** [comment]
I started using the videoview provided by your library and it seems to do the trick for me.
But after all it would be nice if that was fixed in the future! :+1: 
Thanks though.

**Comment by protyposis** [comment]
If the `VideoView` works, then there's nothing to be fixed. The `VideoView` is just using the `MediaPlayer`.
