### ISSUE TITLE
Occasional "Handler on dead thread" exception when backing out of VideoActivity

### ISSUE THREAD

**Issue by oseparovic** [protyposis/ITEC-MediaPlayer#71]
Not a crash but a logged error (probably a `printStackTrace()`). Please close if this is not an issue. Happens SOMETIMES when leaving an active dash video activity. Am I missing some tear-down code?

This is in my `onPause()`

        if (mVideoView.isPlaying()) {
            mVideoView.stopPlayback();
            mVideoView.setVideoSource(null);
        }

And here is the stacktrace

```
W/MessageQueue: Handler (android.os.Handler) {421a1010} sending message to a Handler on a dead thread
java.lang.RuntimeException: Handler (android.os.Handler) {421a1010} sending message to a Handler on a dead thread
at android.os.MessageQueue.enqueueMessage(MessageQueue.java:294)
at android.os.Handler.enqueueMessage(Handler.java:618)
at android.os.Handler.sendMessageAtTime(Handler.java:587)
at android.os.Handler.sendMessageDelayed(Handler.java:558)
at android.os.Handler.sendMessage(Handler.java:495)
at net.protyposis.android.mediaplayer.dash.DashMediaExtractor$2.onSuccess(DashMediaExtractor.java:625)
at net.protyposis.android.mediaplayer.dash.SegmentDownloader$ResponseCallback.onResponse(SegmentDownloader.java:239)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
```

**Comment by protyposis** [comment]
Thanks, this seems to happen when a segment download finishes at the same time the activity is destroyed. Not really a problem, but I'll still fix it for the next version.

**Comment by protyposis** [comment]
Issue is fixed in `4.3.2`.

**Comment by oseparovic** [comment]
Awesome, I'll test it out ASAP and let you know if I see it anymore

**Comment by oseparovic** [comment]
Cannot reproduce. Closing
