### ISSUE TITLE
app crash on illegalStateException

### ISSUE THREAD

**Issue by sgarg17** [protyposis/ITEC-MediaPlayer#77]
seeing several crashes reported due to an illegal state exception from mediaCodecDecoder.release()... ideas on how to prevent this? I just updated to the most recent version of mediaplayer-extended and was able to reproduce the crash with the following stacktrace:

`prepareAsync() failed: something is in a wrong state
                                                                      java.lang.IllegalStateException
                                                                          at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                          at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
                                                                          at net.protyposis.android.mediaplayer.MediaCodecDecoder.queueSampleToCodec(MediaCodecDecoder.java:278)
                                                                          at net.protyposis.android.mediaplayer.Decoders.decodeFrame(Decoders.java:91)
                                                                          at net.protyposis.android.mediaplayer.MediaPlayer.prepareInternal(MediaPlayer.java:447)
                                                                          at net.protyposis.android.mediaplayer.MediaPlayer.access$800(MediaPlayer.java:37)
                                                                          at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.prepareInternal(MediaPlayer.java:1046)
                                                                          at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.handleMessage(MediaPlayer.java:998)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:150)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)`

`E/Decoders: release failed
                                                                   java.lang.IllegalStateException
                                                                       at android.media.MediaCodec.native_stop(Native Method)
                                                                       at android.media.MediaCodec.stop(MediaCodec.java:1901)
                                                                       at net.protyposis.android.mediaplayer.MediaCodecDecoder.release(MediaCodecDecoder.java:587)
                                                                       at net.protyposis.android.mediaplayer.Decoders.release(Decoders.java:124)
                                                                       at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.releaseInternal(MediaPlayer.java:1309)
                                                                       at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.prepareInternal(MediaPlayer.java:1060)
                                                                       at net.protyposis.android.mediaplayer.MediaPlayer$PlaybackThread.handleMessage(MediaPlayer.java:998)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:150)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by protyposis** [comment]
Hi, I have no idea what could cause this, you'd have to provide me an example to debug.
