### ISSUE TITLE
How to stop the video playback?

### ISSUE THREAD

**Issue by t3rmin83r** [protyposis/ITEC-MediaPlayer#8]
The library is good. In the native android video view, there is a stopplayback() method to stop the video. I cannot find such method in this library. I am using pause() to to stop video and assign another http file to start play back but its crashing giving illegal state exception. Can you help me in this?

thanks!

**Comment by protyposis** [comment]
Hi! I haven't mirrored the whole MediaPlayer/VideoView API yet, but am waiting for people like you to help me decide what's needed, so thanks!

I've just pushed a new version 1.4.2 to GitHub and JCenter that adds the stopPlayback() method, and setting a new data source should now work as expected.

**Comment by t3rmin83r** [comment]
Hi, thanks for the update and stopplayback() method is added and working fine. I have found another issue which I may be taking it wrong. In native videoview, when a video finishes and its onComplete callback is called, I can set a new datasource and it plays the new video. While in this your library I have to manually call stopplayback() in onComplete() then it plays the next video otherwise it throws exception. Although I have managed to make it work and serve my purpose but can you have a look on it?

thanks!

**Comment by t3rmin83r** [comment]
One more thing that I guess is creating problem that is when video is playing, user presses the home key to take app to background and comes back after a few seconds, the app crashes. I am pausing the videoview on onPause and resuming the play in onResume of activity and seeking to the position it paused last time but MediaPlayer (mPlayer) has got null and causing the app to crash. Same code is working for native videoView.

**Comment by protyposis** [comment]
The stopPlayback in onComplete issue is fixed in the most recent commit, but I'll wait for more changes before releasing the next version. Thanks again!

I can't reproduce the exception after pausing the app... Did you try the demo app? Do you get an exception there as well? Or can you post the code of a minimum example of your failing activity?

**Comment by t3rmin83r** [comment]
Here is the exception log:

```
java.lang.RuntimeException: Unable to resume activity {com.appdev360.itsrelevanttvapp/com.appdev360.itsrelevanttvapp.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void at.aau.itec.android.mediaplayer.MediaPlayer.seekTo(int)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2976)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3007)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void at.aau.itec.android.mediaplayer.MediaPlayer.seekTo(int)' on a null object reference
       at at.aau.itec.android.mediaplayer.VideoView.seekTo(VideoView.java:319)
       at com.appdev360.itsrelevantapp.bl.AppScreensController.onResume(AppScreensController.java:276)
       at com.appdev360.itsrelevanttvapp.HomeActivity.onResume(HomeActivity.java:389)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
       at android.app.Activity.performResume(Activity.java:6106)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2965)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3007)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

AND here is the minimal code that you requested: (~~I dont know how to format code here :(~~ formatting tags added)

``` java
public class AppScreensController implements MediaPlayer.OnCompletionListener, MediaPlayer.OnErrorListener, MediaPlayer.OnPreparedListener {

private void playVideoWithIndex(int index) {
                        Video video = mStoreData.videoContent.getVideo(index);
            Utils.uriToMediaSourceAsync(activity.getApplicationContext(), Uri.parse(video.url), new Utils.MediaSourceAsyncCallbackHandler() {
                @Override
                public void onMediaSourceLoaded(MediaSource mediaSource) {
                    mVideoView.setVideoSource(mediaSource);
                }

                @Override
                public void onException(Exception e) {

                }
            });

        }


public void onPause() {
           if(mVideoView.isPlaying()) {
               videoPosition = mVideoView.getCurrentPosition();
               mVideoView.pause();
               wasVideoPaused = true;
           }
    }

public void onResume() {
           if(!mVideoView.isPlaying() && wasVideoPaused) {
               wasVideoPaused = false;
               mVideoView.seekTo(videoPosition);
               mVideoView.start();
           }
    }
```

**Comment by t3rmin83r** [comment]
I tried VideoView sample activity from your provided sample and was having same crash issue on onResume() while resuming the video. Please have a look on it.

**Comment by protyposis** [comment]
From your sample code it looks like you are setting the data source asynchronously in playVideoWithIndex(...), but calling onResume() synchronously from the activity - which could lead to onResume() and therefore seekTo(...) being called before the data source has been set, which would lead to an exception.

But since you say that the [demo app](https://play.google.com/store/apps/details?id=at.aau.itec.android.mediaplayerdemo) is crashing as well, that is very odd... which device and Android version are you using?

**Comment by t3rmin83r** [comment]
I am testing on LG G3 and S4

**Comment by protyposis** [comment]
Can't reproduce it on a Note 4 and I have no idea what the difference to the working native VideoView might be, I'm sorry. I think the issue is that the MediaPlayer isn't initialized when you call the seek function, which I think can only happen when no valid datasource is set and the OnPreparedListener has not been invoked. If you figure it out, please let me know.
